# Lab Instructions

Find a dataset that interests you. I'd recommend starting on [Kaggle](https://www.kaggle.com/). Read through all of the material about the dataset and download a .CSV file.

1. Write a short summary of the data.  Where did it come from?  How was it collected?  What are the features in the data?  Why is this dataset interesting to you?  

2. Identify 5 interesting questions about your data that you can answer using Pandas methods.  

3. Answer those questions!  You may use any method you want (including LLMs) to help you write your code; however, you should use Pandas to find the answers.  LLMs will not always write code in this way without specific instruction.  

4. Write the answer to your question in a text box underneath the code you used to calculate the answer.

This dataset is a collection of Dungeons and Dragons 5e monster statistics sourced from Kaggle. The data was scraped from D&D database websites and contains all the basic monsters released in the original Monster Manual. Features in this dataset include the monster's name, challenge rating (CR), type, size, armor class (AC), hit points (HP), alignment, and core stats like Strength, Dexterity, and Constitution. This dataset is interesting to me because it allows us to use data science tools to analyze game balance and find the mathematical extremes of the monsters players face in a campaign.

Which 5 monsters are the ultimate "tanks" with the highest Hit Points?

What is the most common alignment for monsters in the D&D universe?

How does a monster's Size affect its average Armor Class?

What are the top 3 most common types of monsters players will fight?

Which monster has the absolute highest physical Strength score in the game?

In [7]:
import pandas as pd 
df = pd.read_csv('dnd_monsters.csv')

In [8]:
# Question 1: Which 5 monsters are the ultimate "tanks" with the highest Hit Points ?
highest_hp = df.sort_values(by='hp', ascending=False).head(5)
display(highest_hp[['name', 'type', 'hp']])
# According to the data, the Tarrasque has the highest HP at 676, then Tiamat , the Zariel  followed by the Ancient Gold Dragon and the Ancient Red Dragon .

                    name                 type   hp
643            tarrasque  monstrosity (titan)  676
652               tiamat                fiend  615
759               zariel        fiend (devil)  580
36    ancient-red-dragon               dragon  546
34   ancient-gold-dragon               dragon  546

In [9]:
# Question 2: What is the most common alignment for monsters in the D&D universe?
common_alignments = df['align'].value_counts().head(3)
display(common_alignments)
# The most common alignment in this dataset is unaligned with 171 monsters. For monsters with a moral alignment

align
unaligned       171
chaotic evil    151
lawful evil     113
Name: count, dtype: int64

In [10]:
# Question 3: How does a monster's Size affect its average Armor Class (AC)?
size_ac = df.groupby('size')['ac'].mean().sort_values(ascending=False)
display(size_ac)
# The Gargantuan monsters have the highest average Armor Class at 19.8, while Tiny monsters have the lowest average at 12.8.

size
Gargantuan    19.840000
Huge          16.376812
Large         14.666667
Medium        14.267717
Small         12.925926
Tiny          12.842105
Name: ac, dtype: float64

In [11]:
# Question 4: What are the top 3 most common types of monsters players will fight?
common_types = df['type'].value_counts().head(3)
display(common_types)
# The most common monster types players will encounter in this manual are Beasts 106 , followed by monstrosity 75 and humanoid 68.

type
beast                  106
monstrosity             75
humanoid (any race)     68
Name: count, dtype: int64

In [12]:
# Question 5: Which monster has the absolute highest physical Strength score in the game?
max_str = df.sort_values(by='str', ascending=False).head(1)
display(max_str[['name', 'str', 'size', 'cr']])
# the Ancient Red Dragon has the highest strength

                  name   str        size  cr
36  ancient-red-dragon  30.0  Gargantuan  24