In [15]:
import pandas as pd 
df = pd.read_csv('dnd_monsters.csv')

In [16]:
# Question 1: Which 5 monsters are the ultimate "tanks" with the highest Hit Points ?
highest_hp = df.sort_values(by='hp', ascending=False).head(5)
display(highest_hp[['name', 'type', 'hp']])

                    name                 type   hp
643            tarrasque  monstrosity (titan)  676
652               tiamat                fiend  615
759               zariel        fiend (devil)  580
36    ancient-red-dragon               dragon  546
34   ancient-gold-dragon               dragon  546

In [17]:
# Question 2: What is the most common alignment for monsters in the D&D universe?
common_alignments = df['align'].value_counts().head(3)
display(common_alignments)

align
unaligned       171
chaotic evil    151
lawful evil     113
Name: count, dtype: int64

In [18]:
# Question 3: How does a monster's Size affect its average Armor Class (AC)?
size_ac = df.groupby('size')['ac'].mean().sort_values(ascending=False)
display(size_ac)

size
Gargantuan    19.840000
Huge          16.376812
Large         14.666667
Medium        14.267717
Small         12.925926
Tiny          12.842105
Name: ac, dtype: float64

In [19]:
# Question 4: What are the top 3 most common types of monsters players will fight?
common_types = df['type'].value_counts().head(3)
display(common_types)

type
beast                  106
monstrosity             75
humanoid (any race)     68
Name: count, dtype: int64

In [20]:
# Question 5: Which monster has the absolute highest physical Strength score in the game?
max_str = df.sort_values(by='str', ascending=False).head(1)
display(max_str[['name', 'str', 'size', 'cr']])

                  name   str        size  cr
36  ancient-red-dragon  30.0  Gargantuan  24